### ISSUE TITLE
Should we compile this in Harbour, or xHarbour?

### ISSUE THREAD

**Issue by GHExplorer** [ronpinkas/xbase-script#1]
Hi,

Is there an existing pp.exe executable, from the most recent code?

**Comment by ronpinkas** [comment]
Hi, I did not yry myself recently but in principle it should compile and
work correctly.

**Comment by GHExplorer** [comment]
Ok, I'll give it a try in Harbour, thanks.

**Comment by GHExplorer** [comment]
Hi Ron,

So it looks like there are AT() errors.  

Using

hbmk2 pp.prg prgscrpt.prg test.prg tstclass.prg tstole.prg

, it looks like Harbour won't allow more than 2 parameters.



Compiling 'pp.prg'...
pp.prg(2694) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(2698) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(2724) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(2744) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(2809) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(2849) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(2910) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(2911) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(2934) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(2935) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(2964) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(2965) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2
pp.prg(9269) Error E0021  Incorrect number of arguments in AT
Passed: 3, expected: 2

**Comment by ronpinkas** [comment]
Sorry I have not updated xbase-script on GitHub for a long time.

1. The latest xbScript ( it's also PP and DOT) is in a source file called xbscript.prg (xharbor//utils/xbscript).

2. You do NOT need to also compile the other sources you listed - only xbscript.prg.

3. I just looked and it seems I should add a #translate AT( <cSearch>, <cString>, <nStart> [, <nEnd>] ) => hb_At( <cSearch>, <cString>, <nStart> [, <nEnd>] ) - will do asap.

Ron

**Comment by GHExplorer** [comment]
Thanks, Ron.  I'll retry compiling in Harbour, when it's ready.

**Comment by ronpinkas** [comment]
2023-11-01 15:24 UTC-0500 Ron Pinkas <ronpinkas/AT/gmail/com>
   * utils/xbscript/xbscript.prg
     + Added: #include "hbcompat.ch" when compiled under Harbour

You should now be able to compile the latest xbScript (https://github.com/xHarbour-org/xharbour/tree/main/utils/xbscript) with Harbour.

**Comment by GHExplorer** [comment]
Thanks Ron,

I think there's too many subtle differences between Harbour and xHarbour, to compile with minor modifications.

First there was a complaint about the 

`#pragma w2`

declaration. 

After changing it to 

`#pragma -w2`

, it leads to all sorts of warnings & errors.

Sorry about this.  It's not that important, I was curious to see what your version of the Dot Prompt looked like.



xbscript.prg(2634) Warning W0028  Unreachable code
xbscript.prg(2634) Warning W0001  Ambiguous reference 'XVAL'
xbscript.prg(2634) Warning W0001  Ambiguous reference 'XVAL'
xbscript.prg(2637) Warning W0001  Ambiguous reference 'XVAL'
xbscript.prg(2639) Warning W0001  Ambiguous reference 'XVAL'
xbscript.prg(2644) Warning W0001  Ambiguous reference 'XVAL'
xbscript.prg(2648) Warning W0001  Ambiguous reference 'XVAL'
xbscript.prg(2650) Warning W0001  Ambiguous reference 'XVAL'
xbscript.prg(2653) Warning W0006  Procedure returns value
xbscript.prg(2761) Warning W0003  Variable 'I' declared but not used in function 'PP_EXECMETHOD(2660)'
xbscript.prg(3772) Warning W0003  Variable 'NPOS' declared but not used in function 'PARSELINE(3287)'
xbscript.prg(3772) Warning W0003  Variable 'CCHR' declared but not used in function 'PARSELINE(3287)'
xbscript.prg(3772) Warning W0003  Variable 'CPCODE' declared but not used in function 'PARSELINE(3291)'
xbscript.prg(9777) Warning W0003  Variable 'AMATCHRULE' declared but not used in function 'COMPILERULE(8601)'
xbscript.prg(9777) Warning W0003  Variable 'CRULEEXP' declared but not used in function 'COMPILERULE(8601)'
xbscript.prg(9777) Warning W0003  Variable 'NRULE' declared but not used in function 'COMPILERULE(8604)'
xbscript.prg(9777) Warning W0003  Variable 'NRULES' declared but not used in function 'COMPILERULE(8604)'
xbscript.prg(12398) Warning W0003  Variable 'ASTACK' declared but not used in function 'PP_EXEC(12273)'
xbscript.prg(12598) Warning W0028  Unreachable code
xbscript.prg(12752) Warning W0003  Variable 'NSCREENWIDTH' declared but not used in function 'PPINIT$(12711)'
Lines 19516, Functions/Procedures 89
Generating C source output to 'xbscript.c'... Done.
xbscript.c:
Error E2141 xbs_harb.ch 1497: Declaration syntax error
Error E2451 xbs_harb.ch 1506: Undefined symbol 's_bArrayPrefix' in function HB_FUN_SETARRAYPREFIX
Error E2288 xbs_harb.ch 1506: Pointer to structure required on left side of -> or ->* in function HB_FUN_SETARRAYPREFIX
Error E2451 xbs_harb.ch 1513: Undefined symbol 's_bArrayPrefix' in function HB_FUN_GETARRAYPREFIX
Warning W8019 xbs_harb.ch 1524: Code has no effect in function HB_FUN_NEXTTOKEN
Error E2379 xbs_harb.ch 1524: Statement missing ; in function HB_FUN_NEXTTOKEN
Error E2140 xbs_harb.ch 1525: Declaration is not allowed here in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1533: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1539: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1540: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1549: Undefined symbol 'lDontRecord' in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1553: Undefined symbol 'lDontRecord' in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1553: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1601: Undefined symbol 'BYTE' in function HB_FUN_NEXTTOKEN
Error E2121 xbs_harb.ch 1601: Function call missing ) in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1631: Undefined symbol 'BYTE' in function HB_FUN_NEXTTOKEN
Error E2121 xbs_harb.ch 1631: Function call missing ) in function HB_FUN_NEXTTOKEN
Error E2448 xbs_harb.ch 1901: Undefined label 'Done' in function HB_FUN_NEXTTOKEN
Warning W8004 xbs_harb.ch 1901: 'Counter' is assigned a value that is never used in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1912: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTIDENTIFIER
Error E2288 xbs_harb.ch 1917: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTIDENTIFIER
Error E2288 xbs_harb.ch 1918: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTIDENTIFIER
Error E2451 xbs_harb.ch 1951: Undefined symbol 'BYTE' in function HB_FUN_NEXTIDENTIFIER
Error E2121 xbs_harb.ch 1951: Function call missing ) in function HB_FUN_NEXTIDENTIFIER
Error E2451 xbs_harb.ch 1993: Undefined symbol 'BYTE' in function HB_FUN_NEXTIDENTIFIER
Error E2121 xbs_harb.ch 1993: Function call missing ) in function HB_FUN_NEXTIDENTIFIER
Warning W8004 xbs_harb.ch 2033: 'cLastChar' is assigned a value that is never used in function HB_FUN_NEXTIDENTIFIER
Error E2288 xbs_harb.ch 2040: Pointer to structure required on left side of -> or ->* in function HB_FUN_EXTRACTLEADINGW
S
Error E2228 xbs_harb.ch 2040: Too many error or warning messages in function HB_FUN_EXTRACTLEADINGWS
*** 26 errors in Compile ***

C compile error.

**Comment by ronpinkas** [comment]
Please remember that originally it compiled even with Clipper - it should be no problem at all making it work correctly with xHarbour if you are willing to invest minimal time. :)

1. I Protected the #pragma W2 for xHarbour only.
2. I added an #xuntranslate THROW for Harbour - should fix the xbscript.prg issues.
3. I added HB_LEGACY_TYPES_ON which should fix the xbs_harb.ch issues.

Let me know if more changes needed.

**Comment by GHExplorer** [comment]
Thanks for taking the time, Ron.  I'll play with it today and through the weekend, try to make it work.

I'm using Harbour, so will approach it from that angle.

**Comment by ronpinkas** [comment]
Sorry I meant to say ‘it should be no problem at all making it work correctly with Harbour’ - I am here to assist as needed.

**Comment by GHExplorer** [comment]
Remaining errors all related to xbs_harb.ch.

Should we just replace that with a Harbour equivalent, if there is one?

Error E2056 xbs_harb.ch 1487: Misplaced endif directive
Error E2141 xbs_harb.ch 1505: Declaration syntax error
Error E2451 xbs_harb.ch 1514: Undefined symbol 's_bArrayPrefix' in function HB_FUN_SETARRAYPREFIX
Error E2288 xbs_harb.ch 1514: Pointer to structure required on left side of -> or ->* in function HB_FUN_SETARRAYPREFI
Error E2451 xbs_harb.ch 1521: Undefined symbol 's_bArrayPrefix' in function HB_FUN_GETARRAYPREFIX
Warning W8019 xbs_harb.ch 1532: Code has no effect in function HB_FUN_NEXTTOKEN
Error E2379 xbs_harb.ch 1532: Statement missing ; in function HB_FUN_NEXTTOKEN
Error E2140 xbs_harb.ch 1533: Declaration is not allowed here in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1541: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1547: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1548: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1557: Undefined symbol 'lDontRecord' in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1561: Undefined symbol 'lDontRecord' in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1561: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1609: Undefined symbol 'BYTE' in function HB_FUN_NEXTTOKEN
Error E2121 xbs_harb.ch 1609: Function call missing ) in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1639: Undefined symbol 'BYTE' in function HB_FUN_NEXTTOKEN
Error E2121 xbs_harb.ch 1639: Function call missing ) in function HB_FUN_NEXTTOKEN
Error E2448 xbs_harb.ch 1909: Undefined label 'Done' in function HB_FUN_NEXTTOKEN
Warning W8004 xbs_harb.ch 1909: 'Counter' is assigned a value that is never used in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1920: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTIDENTIFIE
Error E2288 xbs_harb.ch 1925: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTIDENTIFIE
Error E2288 xbs_harb.ch 1926: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTIDENTIFIE
Error E2451 xbs_harb.ch 1959: Undefined symbol 'BYTE' in function HB_FUN_NEXTIDENTIFIER
Error E2121 xbs_harb.ch 1959: Function call missing ) in function HB_FUN_NEXTIDENTIFIER
Error E2451 xbs_harb.ch 2001: Undefined symbol 'BYTE' in function HB_FUN_NEXTIDENTIFIER
Error E2121 xbs_harb.ch 2001: Function call missing ) in function HB_FUN_NEXTIDENTIFIER
Error E2228 xbs_harb.ch 2001: Too many error or warning messages in function HB_FUN_NEXTIDENTIFIER

**Comment by ronpinkas** [comment]
I am so sorry. I had a bad typo. Can you please try again. There may still
be few left but it should be much better

**Comment by GHExplorer** [comment]
I feel better now.  I make those kinds of mistakes often.

Ok, hang on...

**Comment by GHExplorer** [comment]
There are fewer errors, like you said.

Error E2141 xbs_harb.ch 1505: Declaration syntax error
Error E2451 xbs_harb.ch 1514: Undefined symbol 's_bArrayPrefix' in function HB_FUN_SETARRAYPREFIX
Error E2288 xbs_harb.ch 1514: Pointer to structure required on left side of -> or ->* in function HB_FUN_SETARRAYPREFIX
Error E2451 xbs_harb.ch 1521: Undefined symbol 's_bArrayPrefix' in function HB_FUN_GETARRAYPREFIX
Warning W8019 xbs_harb.ch 1532: Code has no effect in function HB_FUN_NEXTTOKEN
Error E2379 xbs_harb.ch 1532: Statement missing ; in function HB_FUN_NEXTTOKEN
Error E2140 xbs_harb.ch 1533: Declaration is not allowed here in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1541: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1547: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1548: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1557: Undefined symbol 'lDontRecord' in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1561: Undefined symbol 'lDontRecord' in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1561: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1609: Undefined symbol 'BYTE' in function HB_FUN_NEXTTOKEN
Error E2121 xbs_harb.ch 1609: Function call missing ) in function HB_FUN_NEXTTOKEN
Error E2451 xbs_harb.ch 1639: Undefined symbol 'BYTE' in function HB_FUN_NEXTTOKEN
Error E2121 xbs_harb.ch 1639: Function call missing ) in function HB_FUN_NEXTTOKEN
Error E2448 xbs_harb.ch 1909: Undefined label 'Done' in function HB_FUN_NEXTTOKEN
Warning W8004 xbs_harb.ch 1909: 'Counter' is assigned a value that is never used in function HB_FUN_NEXTTOKEN
Error E2288 xbs_harb.ch 1920: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTIDENTIFIER
Error E2288 xbs_harb.ch 1925: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTIDENTIFIER
Error E2288 xbs_harb.ch 1926: Pointer to structure required on left side of -> or ->* in function HB_FUN_NEXTIDENTIFIER
Error E2451 xbs_harb.ch 1959: Undefined symbol 'BYTE' in function HB_FUN_NEXTIDENTIFIER
Error E2121 xbs_harb.ch 1959: Function call missing ) in function HB_FUN_NEXTIDENTIFIER
Error E2451 xbs_harb.ch 2001: Undefined symbol 'BYTE' in function HB_FUN_NEXTIDENTIFIER
Error E2121 xbs_harb.ch 2001: Function call missing ) in function HB_FUN_NEXTIDENTIFIER
Warning W8004 xbs_harb.ch 2041: 'cLastChar' is assigned a value that is never used in function HB_FUN_NEXTIDENTIFIER
Error E2288 xbs_harb.ch 2048: Pointer to structure required on left side of -> or ->* in function HB_FUN_EXTRACTLEADINGW
S
Error E2228 xbs_harb.ch 2048: Too many error or warning messages in function HB_FUN_EXTRACTLEADINGWS
*** 26 errors in Compile ***

**Comment by ronpinkas** [comment]
Thanks.

I did fix and tested with Harbour to compile correctly. I have move xbScript to be a standalone repo which can be added easily as a sub module for Harbour with the following:

   1. <change dir to your harbour core>
   2. git submodule add https://github.com/ronpinkas/xbScript.git contrib/xbscript

This will place the latest xbScript in contrib/xbscript

Then you can build with the following:

   hbmk2 -cflag=-D_HB_API_INTERNAL_ xbscript.prg

Then to test DOT Prompt just type; xbscript

Good luck,

Ron

**Comment by GHExplorer** [comment]
I'll give it a try today, thanks Ron.

**Comment by GHExplorer** [comment]
Hi Ron,

I was able to get this to compile, thanks.

**Comment by ronpinkas** [comment]
Mote importantly does it run correctly for you?

**Comment by GHExplorer** [comment]
It's great.  I haven't tried every command yet, but it's nice prompt tool.  Pasting from the clipboard is a little slow, but still workable.

I mentioned on one of the Google Groups that I'm trying to build in the SQLRDD libraries.  This has been my dream for several years, to work with databases from an xbase style repl.  

Even the most recent version of the Dbase 2019 prompt depends on the legacy BDE drivers, and they aren't perfect.


Having a few problems building with SQLRDD, but that will take some trial & error before I figure out the correct libraries and command line options.

For example, when I use -lSQLBCC58 or -l SQLBCC58 on the hbmk2 command line, it insists the library isn't found.  The LIB env variable is pointing to 

d:\xhbsource\xHarbourBuilder\xHarbour-SQLRDD\bc5\lib

and the harbour lib path.

If I use

set HB_LIBLIST= SQLBCC58.lib

, there's still several missing external errors.

I added the minimums

REQUEST SQLRDD
REQUEST SR_ODBC            

#include "sqlextern.ch"
#include "sqlrdd.ch"       

in the source code, and also included a SQL define.

Anyway, this is just a matter of trial & error and looking through the docs, I'll get there.  You got me past the rough spots, that was good of you.

**Comment by ronpinkas** [comment]
Cool. I am not familiar with hbmk2 but I believe I saw some reports of
someone able to build with Harbour. Try asking on the Harbour's Users
Group. Also a good person to ask for help is Luiz Rafael.Culik

**Comment by GHExplorer** [comment]
Ron, I'm sorry.  I just realized before you responded, that I'm mixing Harbour and xHarbour libraries.

So let me ask you this - what command line should I use, if I'm trying to build xbscript with xHarbour rather than Harbour?

**Comment by ronpinkas** [comment]
That depends on the O/S but essentially it's just the make or batch file
for you environment and just passing it xbscript as the argument.

**Comment by GHExplorer** [comment]
So if we're using Borland bcc82 Windows, I would just use Make against the Makefile in that folder. 

Ok, I'll set up all the environmental variables for xhb, and try it in the morning.  Thanks for your help.

**Comment by ronpinkas** [comment]
There should be a batch file something like bld_b32.bat

**Comment by GHExplorer** [comment]
Hi Ron,

I tried the harbour google group, regarding a missing external, when using the bld.bat in xHarbour (which calls bld_b32.bat).

The missing external error 

___get_std_stream' referenced from C:\XHB\LIB\COMMON.LIB|hbtrace

is showing up when trying to compile using bld.bat in the \xhb\bin folder.

No response on the group, so I opened a ticket in the xharbour github Issue tab.

The error occurs when trying to compile any source, not only xbscript.

**Comment by ronpinkas** [comment]
Did you download the latest binary distribution from xharbour.org or did
you build xharbour yourself from sources?

You should use the compiler specific batch files. Luke make_b32.bat to
build xharbour itself.and bld_b32.bat to build apps like the tests.

**Comment by GHExplorer** [comment]
I'm using the latest binary distribution for the xharbour executables, but bld.bat and bld_b32.bat from the source.

The binary distribution doesn't contain these bld batch files.

However, I just found something out.  The binary distribution I'm using, assumes bcc770.  There's not recent distribution for 582.

I'll reset the variables to point to bcc770.

Do you have a preference, as to which c compiler you like to use?  In terms of convenience, do you prefer Mingw, Msvc, or bcc?

**Comment by GHExplorer** [comment]
Hi Ron,

I'll close this thread, and respond to the xharbour github thread, since it's a different topic.

**Comment by ronpinkas** [comment]
I believe free latest MS Bc is best choice
